### ISSUE TITLE
myQ API Pendaticism Update: Friendly Pointer.

### ISSUE THREAD

**Issue by hjdhjd** [Python-MyQ/Python-MyQ#23]
Friendly pointer to @Lash-L and team...I've just pushed a substantive update to my reference implementation at https://github.com/hjdhjd/myq.

I've gone through and essentially re-entered into the game of "mirror the app behavior" that myQ seems to be marching toward in their effort to become more pedantic about how you access the API. Just wanted to be helpful to the other myQ projects out there. The behavior in my implementation now essentially mirrors the native myQ app behavior when it comes to accessing the API, inclusive of all the headers (even the occasional typos and weirdness they choose to do or not do). I have opted to retain every aspect of the native app's behavior I can, even those that appear incomplete or incorrect, in an effort to "blend in", as it were.

My suggestion would be to adopt a similar approach. I suspect over time we're going to re-enter into a cat-and-mouse game now when it comes to the headers - especially when it comes to the app version.

Enjoy!

**Comment by Lash-L** [comment]
Thanks for all of your work on your side @hjdhjd. It is much appreciated! Hopefully myq calms down a bit in regards to trying to block requests.

**Comment by hjdhjd** [comment]
I wish you luck with all the inevitable support requests. It’s exhausting and people struggle to be reasonable. If you have questions…don’t hesitate to reach out. Discord’s a good way to ping me if you’ve got some questions. I’ll close this request. 😄

**Comment by Lash-L** [comment]
I believe I sent you a friend request on discord

**Comment by hjdhjd** [comment]
Don’t think so…find me on the Homebridge discord and send me a PM.
